[package]
name = "egor00f/cooldownlib"

description = "just small library for call function with cooldown"

version = "0.1.2"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "MIT"

repository = "https://github.com/Ukuroks-games/cooldownLib"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

private = false

[dependencies]

[server-dependencies]


[dev-dependencies]
